#!/bin/bash
set -euo pipefail

echo "=== Shopping Concierge Agent Deployment ==="

# Read parameters from tfvars if present (generated by the packaging service)
if [ -f deploy.auto.tfvars.json ]; then
  export AWS_REGION=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('aws_region','us-east-1'))")
  SERP_KEY=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('serp_api_key',''))")
  DEPLOY_NAME=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('project_name','shopping'))")
else
  SERP_KEY=""
  DEPLOY_NAME="shopping"
fi

# Sanitize identifier for Amplify (alphanumeric only, no hyphens/underscores, max 14 chars)
AMPLIFY_ID=$(echo "$DEPLOY_NAME" | sed 's/[-_]//g' | tr '[:upper:]' '[:lower:]' | cut -c1-14)
echo "Deployment name: $DEPLOY_NAME (Amplify ID: $AMPLIFY_ID)"

# Write sanitized ID to deployment-config.json (Amplify rejects hyphens)
echo "{\"deploymentId\": \"$AMPLIFY_ID\"}" > deployment-config.json

# Store SERP API key in SSM if provided
if [ -n "${SERP_KEY:-}" ] && [ "$SERP_KEY" != "" ]; then
  echo "Setting SERP API key in SSM Parameter Store..."
  aws ssm put-parameter \
    --name "/concierge-agent/${DEPLOY_NAME}/serp-api-key" \
    --value "$SERP_KEY" \
    --type "SecureString" \
    --overwrite \
    --region "${AWS_REGION:-us-east-1}" || echo "Warning: Failed to set SERP API key"
fi

# Install Amplify CLI if not present
if ! command -v ampx &>/dev/null; then
  echo "Installing Amplify CLI..."
  npm install -g @aws-amplify/backend-cli@latest
fi

# Ensure CDK is bootstrapped in this account/region
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "Bootstrapping CDK in $ACCOUNT_ID / $AWS_REGION..."
npx cdk bootstrap "aws://$ACCOUNT_ID/$AWS_REGION" 2>&1 || {
  echo "ERROR: CDK bootstrap failed. Ensure the CodeBuild role has CloudFormation permissions."
  exit 1
}

# Install root dependencies (includes amplify workspace)
npm install
cd amplify && npm install && cd ..

# Step 1: Amplify Backend (Cognito, DynamoDB, AppSync)
echo "=== Step 1/4: Deploying Amplify backend ==="
npm run deploy:amplify || { echo "ERROR: Amplify backend deployment failed"; exit 1; }

# Step 2: MCP Servers (Cart + Shopping)
echo "=== Step 2/4: Deploying MCP servers ==="
npm run deploy:mcp || { echo "ERROR: MCP servers deployment failed"; exit 1; }

# Fix script permissions
chmod +x scripts/*.sh 2>/dev/null || true

# Step 3: Agent (Runtime + Gateway + Memory)
echo "=== Step 3/4: Deploying agent ==="
npm run deploy:agent || { echo "ERROR: Agent deployment failed"; exit 1; }

# Step 4: Frontend (CloudFront + S3)
echo "=== Step 4/4: Deploying frontend ==="
npm run deploy:frontend || { echo "ERROR: Frontend deployment failed"; exit 1; }

# Collect outputs from CloudFormation stacks
echo "=== Collecting deployment outputs ==="
python3 -c "
import boto3, json, os
cf = boto3.client('cloudformation', region_name=os.environ.get('AWS_REGION', 'us-east-1'))
outputs = {'deployment_id': os.environ.get('DEPLOYMENT_ID', ''), 'status': 'success'}

import re

def shorten_key(key):
    \"\"\"Shorten long CDK-generated output keys to readable names.\"\"\"
    # Already short and readable
    if len(key) < 50:
        return key
    # Extract meaningful suffix: find last CamelCase segment with a known pattern
    # e.g. '...ChatMessageTable80360C7BTableArn' -> 'ChatMessageTableArn'
    # e.g. '...GraphQLAPIC644244FGraphQLUrl' -> 'GraphQLUrl'
    # Strip hash-like segments (8+ hex chars)
    cleaned = re.sub(r'[0-9A-Fa-f]{8,}', '', key)
    # Find the last meaningful segments (after 'amplifyData' or 'amplifyAuth')
    for prefix in ['amplifyData', 'amplifyAuth', 'data', 'auth']:
        idx = cleaned.rfind(prefix)
        if idx >= 0:
            cleaned = cleaned[idx + len(prefix):]
            break
    # Remove leading/trailing non-alpha
    cleaned = re.sub(r'^[^A-Za-z]+', '', cleaned)
    return cleaned if cleaned else key[:60]

# Find all stacks related to this deployment
paginator = cf.get_paginator('list_stacks')
for page in paginator.paginate(StackStatusFilter=['CREATE_COMPLETE', 'UPDATE_COMPLETE']):
    for stack in page['StackSummaries']:
        name = stack['StackName']
        if '$AMPLIFY_ID' in name or 'concierge' in name.lower() or 'agentstack' in name.lower() or 'cartstack' in name.lower() or 'shoppingstack' in name.lower() or 'frontendstack' in name.lower():
            try:
                desc = cf.describe_stacks(StackName=name)['Stacks'][0]
                for o in desc.get('Outputs', []):
                    short_key = shorten_key(o['OutputKey'])
                    outputs[short_key] = o['OutputValue']
            except: pass
# Create a default demo user in Cognito (if User Pool exists in outputs)
user_pool_id = None
for k, v in outputs.items():
    if 'UserPoolId' in k or 'userpoolid' in k.lower():
        user_pool_id = v
        break

if user_pool_id:
    demo_email = 'admin@demo.com'
    demo_password = 'Demo1234!'
    outputs['demo_user'] = demo_email
    outputs['demo_password'] = demo_password
    outputs['cognito_user_pool_id'] = user_pool_id
    try:
        cognito = boto3.client('cognito-idp', region_name=os.environ.get('AWS_REGION', 'us-east-1'))
        try:
            cognito.admin_create_user(
                UserPoolId=user_pool_id,
                Username=demo_email,
                UserAttributes=[
                    {'Name': 'email', 'Value': demo_email},
                    {'Name': 'email_verified', 'Value': 'true'},
                    {'Name': 'given_name', 'Value': 'Demo'},
                    {'Name': 'family_name', 'Value': 'User'},
                ],
                TemporaryPassword=demo_password,
                MessageAction='SUPPRESS',
            )
            cognito.admin_set_user_password(
                UserPoolId=user_pool_id,
                Username=demo_email,
                Password=demo_password,
                Permanent=True,
            )
            print(f'Created demo user: {demo_email}')
        except cognito.exceptions.UsernameExistsException:
            print(f'Demo user already exists: {demo_email}')
    except Exception as e:
        print(f'Warning: Could not create demo user: {e}')

# Promote AmplifyUrl to a clear frontend_url key
for k, v in outputs.items():
    if k == 'AmplifyUrl' and v:
        outputs['frontend_url'] = v
        break

json.dump(outputs, open('/tmp/outputs.json', 'w'))
print(f'Collected {len(outputs)} outputs')
" || { echo '{"deployment_id":"'$DEPLOYMENT_ID'","status":"success"}' > /tmp/outputs.json; }

echo "=== Deployment complete ==="
