#!/bin/bash
# Setup web-ui .env.local from deployment outputs
set -e

echo "🚀 Setting up Web UI environment..."

# Get deployment ID
DEPLOYMENT_ID=$(node -p "require('./deployment-config.json').deploymentId" 2>/dev/null || echo "default")
STACK_NAME="AgentStack-${DEPLOYMENT_ID}"

# Parse flags
FORCE=false
for arg in "$@"; do
    case $arg in
        --force) FORCE=true ;;
    esac
done

# Check if .env.local exists
if [[ -f "web-ui/.env.local" && "$FORCE" == "false" ]]; then
    echo "⚠️  web-ui/.env.local already exists"
    echo "   Run with --force to regenerate"
    exit 0
fi

# Get CDK outputs from CloudFormation
echo "📊 Querying ${STACK_NAME}..."
REGION_FLAG="${AWS_REGION:-us-east-1}"
CDK_OUTPUTS=$(aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION_FLAG" --query "Stacks[0].Outputs" --output json 2>/dev/null) || {
    echo "❌ Could not query ${STACK_NAME}. Deploy agent stack first."
    exit 1
}

# Parse CDK outputs
RUNTIME_ARN=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeArn") | .OutputValue // empty')
RUNTIME_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MainRuntimeId") | .OutputValue // empty')
MEMORY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="MemoryId") | .OutputValue // empty')
GATEWAY_URL=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayUrl") | .OutputValue // empty')
GATEWAY_ID=$(echo "$CDK_OUTPUTS" | jq -r '.[] | select(.OutputKey=="GatewayId") | .OutputValue // empty')

# Read Amplify outputs
if [[ ! -f "amplify_outputs.json" ]]; then
    echo "❌ amplify_outputs.json not found. Deploy Amplify first."
    exit 1
fi

REGION=$(jq -r '.custom.region // empty' amplify_outputs.json)
REGION=${REGION:-${AWS_REGION:-us-east-1}}
USER_POOL_ID=$(jq -r '.auth.user_pool_id // empty' amplify_outputs.json)
USER_POOL_CLIENT_ID=$(jq -r '.auth.user_pool_client_id // empty' amplify_outputs.json)

# Validate required values
if [[ -z "$RUNTIME_ARN" || -z "$USER_POOL_ID" || -z "$USER_POOL_CLIENT_ID" ]]; then
    echo "❌ Missing required values. Ensure both stacks are deployed."
    exit 1
fi

# Generate .env.local
cat > web-ui/.env.local << EOF
# Auto-generated by setup-web-ui-env.sh
# Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# AWS Configuration
VITE_AWS_REGION=${REGION}

# Cognito Configuration
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}

# Agent Runtime Configuration
VITE_AGENT_RUNTIME_ARN=${RUNTIME_ARN}
VITE_AGENT_RUNTIME_ID=${RUNTIME_ID}
VITE_AGENT_ENDPOINT_NAME=DEFAULT

# Memory Configuration
VITE_MEMORY_ID=${MEMORY_ID}

# Gateway Configuration
VITE_GATEWAY_URL=${GATEWAY_URL}
VITE_GATEWAY_ID=${GATEWAY_ID}

# Payment Integration (mock mode only)
VITE_PAYMENT_MOCK_MODE=true
EOF

echo "✅ Created web-ui/.env.local"
echo ""
echo "Next: cd web-ui && npm run dev"
