[theme]
primaryColor = "#ff8400"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#fafafa"
textColor = "#32373c"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
