variable "name_prefix" {
  type        = string
  description = "Shared control-plane resource prefix (e.g. ava-cp-dev-982569)"
}

variable "registry_name" {
  type        = string
  description = "Registry name. Must start with letter/digit. Allowed: a-z A-Z 0-9 _ - . / (<=64 chars)."
  default     = "app-factory-agents"
}

variable "registry_description" {
  type        = string
  default     = "Catalog of agents generated by the AVA App Factory"
}

variable "auto_approve" {
  type        = bool
  description = "If true, records are immediately searchable without curator review. Turn off for prod."
  default     = true
}

variable "tags" {
  type    = map(string)
  default = {}
}
