# ${PROJECT_NAME} - Multi-Agent Orchestration on AgentCore
# Generated by Control Plane

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}
