#!/bin/bash
set -euo pipefail

echo "=== Market Surveillance Deployment ==="

# Read parameters from tfvars if present (generated by the packaging service)
if [ -f deploy.auto.tfvars.json ]; then
  export AWS_REGION=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('aws_region','us-east-1'))")
  DEPLOY_NAME=$(python3 -c "import json; print(json.load(open('deploy.auto.tfvars.json')).get('project_name','market-surveillance'))")
else
  DEPLOY_NAME="market-surveillance"
fi

ENVIRONMENT="dev"
echo "Deployment name: $DEPLOY_NAME"
echo "Environment: $ENVIRONMENT"
echo "Region: $AWS_REGION"

# Remove auto-generated tfvars to avoid "undeclared variable" warnings in Terraform
# (the packaging service generates project_name/aws_region but Market Surveillance doesn't use them)
rm -f deploy.auto.tfvars.json
rm -f infrastructure/foundations/deploy.auto.tfvars.json
rm -f infrastructure/app-infra/deploy.auto.tfvars.json

# Prerequisite (one-time, account-level): The Terraform module creates an
# aws_cloudwatch_log_delivery.traces resource that routes AgentCore traces
# through X-Ray → CloudWatch Logs. That pipeline requires the account's X-Ray
# trace segment destination to be "CloudWatchLogs" AND a CloudWatch Logs
# resource policy granting xray.amazonaws.com write access to aws/spans.
# Neither can be done by this script at deploy time — CodeBuild's service
# role doesn't have xray:UpdateTraceSegmentDestination or logs:PutResourcePolicy.
#
# Operators must run these commands ONCE per account/region before the first
# deploy (the UI surfaces the same instructions in a prerequisites banner):
#
#   aws logs put-resource-policy --policy-name AWSServiceRoleForXRayLogs \
#     --policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow",
#     "Principal":{"Service":"xray.amazonaws.com"},"Action":"logs:PutLogEvents",
#     "Resource":"arn:aws:logs:REGION:ACCOUNT:log-group:aws/spans:*"}]}'
#
#   aws xray update-trace-segment-destination --destination CloudWatchLogs \
#     --region REGION

# Step 1: Deploy backend infrastructure (Terraform foundations + app-infra)
echo "=== Step 1/3: Deploying backend infrastructure ==="
chmod +x scripts/*.sh 2>/dev/null || true
scripts/deploy-backend.sh --environment "$ENVIRONMENT" --auto-approve || {
  echo "ERROR: Backend infrastructure deployment failed"
  exit 1
}

# Step 2: Deploy webapp (Docker build + push + ASG refresh)
echo "=== Step 2/3: Deploying web application ==="
scripts/deploy-webapp-ec2.sh --environment "$ENVIRONMENT" || {
  echo "ERROR: Web application deployment failed"
  exit 1
}

# Step 3: Seed Database (if tables don't exist)
echo "=== Step 3/3: Seeding database ==="

# Ensure session-manager-plugin is installed for the SSM port-forward to RDS
# through the bastion. Not bundled with the AL2 CodeBuild image; the
# .deb/.rpm installer is idempotent (no-op if already present).
if ! command -v session-manager-plugin >/dev/null 2>&1; then
  echo "Installing session-manager-plugin..."
  arch=$(uname -m)
  case "$arch" in
    aarch64|arm64) sm_url="https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_arm64/session-manager-plugin.rpm" ;;
    x86_64|amd64)  sm_url="https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64/session-manager-plugin.rpm" ;;
    *)             echo "  ⚠️  Unsupported arch $arch — skipping seeding" ; sm_url="" ;;
  esac
  if [ -n "$sm_url" ]; then
    curl -fsSL "$sm_url" -o /tmp/smp.rpm && \
      (rpm -i /tmp/smp.rpm 2>/dev/null || yum install -y /tmp/smp.rpm >/dev/null 2>&1 || sudo rpm -i /tmp/smp.rpm 2>/dev/null || true)
    command -v session-manager-plugin >/dev/null 2>&1 \
      && echo "  ✓ session-manager-plugin installed" \
      || echo "  ⚠️  session-manager-plugin install failed — seeding will skip"
  fi
fi

echo "Checking if database needs seeding..."

# Get database credentials from Secrets Manager
DB_SECRET=$(aws secretsmanager get-secret-value \
  --secret-id "market-surveillance-db-${ENVIRONMENT}" \
  --region "$AWS_REGION" \
  --query SecretString --output text 2>/dev/null) || {
  echo "Warning: Could not retrieve database credentials. Skipping seeding."
  DB_SECRET=""
}

if [ -n "$DB_SECRET" ]; then
  DB_USERNAME=$(echo "$DB_SECRET" | python3 -c "import sys, json; print(json.load(sys.stdin)['USERNAME'])")
  DB_PASSWORD=$(echo "$DB_SECRET" | python3 -c "import sys, json; print(json.load(sys.stdin)['PASSWORD'])")
  DB_NAME=$(echo "$DB_SECRET" | python3 -c "import sys, json; print(json.load(sys.stdin)['DBNAME'])")
  DB_HOST=$(echo "$DB_SECRET" | python3 -c "import sys, json; print(json.load(sys.stdin)['HOST'])")

  # Get bastion instance ID
  BASTION_INSTANCE=$(aws ec2 describe-instances \
    --region "$AWS_REGION" \
    --filters "Name=tag:Name,Values=market-surveillance-${ENVIRONMENT}-bastion-host" "Name=instance-state-name,Values=running" \
    --query "Reservations[0].Instances[0].InstanceId" --output text 2>/dev/null)

  if [ -n "$BASTION_INSTANCE" ] && [ "$BASTION_INSTANCE" != "None" ]; then
    echo "Setting up port forwarding through bastion $BASTION_INSTANCE..."

    # Start SSM port forward in background
    aws ssm start-session \
      --target "$BASTION_INSTANCE" \
      --document-name AWS-StartPortForwardingSessionToRemoteHost \
      --parameters "{\"host\":[\"$DB_HOST\"],\"portNumber\":[\"5432\"],\"localPortNumber\":[\"5940\"]}" \
      --region "$AWS_REGION" > /tmp/ssm-session.log 2>&1 &
    SSM_PID=$!

    # Wait for port to be available
    echo "Waiting for port forward to establish..."
    for i in {1..30}; do
      if nc -z localhost 5940 2>/dev/null; then
        echo "Port forward established"
        break
      fi
      sleep 1
    done

    if ! nc -z localhost 5940 2>/dev/null; then
      # Surface SSM session output so the real failure is diagnosable. Silent
      # skips (e.g. AccessDenied on ssm:StartSession) previously manifested as
      # a generic "Could not establish port forward" with no root cause.
      if [ -s /tmp/ssm-session.log ]; then
        echo "--- ssm start-session output ---"
        cat /tmp/ssm-session.log
        echo "--- end ssm output ---"
      fi
    fi

    if nc -z localhost 5940 2>/dev/null; then
      # Install Python dependencies
      echo "Installing seeding script dependencies..."
      python3 -m pip install -q psycopg[binary] PyYAML || {
        echo "Warning: Failed to install Python dependencies"
      }

      # Check if database is already seeded
      export DB_PASSWORD="$DB_PASSWORD"
      TABLE_COUNT=$(python3 -c "
import psycopg
try:
    conn = psycopg.connect('host=localhost port=5940 dbname=$DB_NAME user=$DB_USERNAME password=$DB_PASSWORD')
    cur = conn.cursor()
    cur.execute(\"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public'\")
    count = cur.fetchone()[0]
    print(count)
    conn.close()
except Exception as e:
    print('0')
" 2>/dev/null)

      if [ "$TABLE_COUNT" = "0" ] || [ -z "$TABLE_COUNT" ]; then
        echo "Database is empty. Initializing schema and seeding data..."

        # Initialize schema
        python3 -m seeding_scripts.db_ops.db_init \
          --database "$DB_NAME" \
          --host localhost \
          --port 5940 \
          --user "$DB_USERNAME" \
          --no-ssl || echo "Warning: Schema initialization failed"

        # Generate synthetic data
        python3 -m seeding_scripts.data_gen \
          --seed 42 \
          --output-dir ./seeding_scripts/synthetic_data || echo "Warning: Data generation failed"

        # Load data
        python3 -m seeding_scripts.database_seeding \
          --input-dir ./seeding_scripts/synthetic_data \
          --database "$DB_NAME" \
          --host localhost \
          --port 5940 \
          --user "$DB_USERNAME" || echo "Warning: Data loading failed"

        echo "Database seeding complete"
      else
        echo "Database already has $TABLE_COUNT tables. Skipping seeding."
      fi

      # Cleanup SSM session
      kill $SSM_PID 2>/dev/null || true
    else
      echo "Warning: Could not establish port forward. Skipping database seeding."
      kill $SSM_PID 2>/dev/null || true
    fi
  else
    echo "Warning: Bastion instance not found. Skipping database seeding."
  fi
else
  echo "Warning: Database credentials not available. Skipping database seeding."
fi

# Collect outputs
echo "=== Collecting deployment outputs ==="
python3 -c "
import boto3, json, os

region = os.environ.get('AWS_REGION', 'us-east-1')
env = '$ENVIRONMENT'
ssm = boto3.client('ssm', region_name=region)
outputs = {'deployment_id': os.environ.get('DEPLOYMENT_ID', ''), 'status': 'success'}

params_to_check = {
    'ui_url': f'/market-surveillance/{env}/foundations/cloudfront/domain',
    'api_endpoint': f'/market-surveillance/{env}/app-infra/api-gateway/endpoint',
    'cognito_user_pool_id': f'/market-surveillance/{env}/foundations/cognito/user-pool-id',
    'cognito_client_id': f'/market-surveillance/{env}/foundations/cognito/web-app-client-id',
    'cognito_hosted_ui': f'/market-surveillance/{env}/foundations/cognito/hosted-ui-url',
    'alb_dns': f'/market-surveillance/{env}/foundations/alb/dns-name',
}

# Create a default demo user in Cognito
try:
    user_pool_id = ssm.get_parameter(Name=f'/market-surveillance/{env}/foundations/cognito/user-pool-id')['Parameter']['Value']
    cognito = boto3.client('cognito-idp', region_name=region)
    demo_email = 'admin@example.com'
    demo_password = 'Demo1234!'
    try:
        cognito.admin_create_user(
            UserPoolId=user_pool_id,
            Username=demo_email,
            UserAttributes=[
                {'Name': 'email', 'Value': demo_email},
                {'Name': 'email_verified', 'Value': 'true'},
            ],
            TemporaryPassword=demo_password,
            MessageAction='SUPPRESS',
        )
        cognito.admin_set_user_password(
            UserPoolId=user_pool_id,
            Username=demo_email,
            Password=demo_password,
            Permanent=True,
        )
        outputs['demo_user'] = demo_email
        outputs['demo_password'] = demo_password
        print(f'Created demo user: {demo_email}')
    except cognito.exceptions.UsernameExistsException:
        outputs['demo_user'] = demo_email
        outputs['demo_password'] = demo_password
        print(f'Demo user already exists: {demo_email}')
except Exception as e:
    print(f'Warning: Could not create demo user: {e}')

for key, param_name in params_to_check.items():
    try:
        val = ssm.get_parameter(Name=param_name)['Parameter']['Value']
        if key == 'ui_url' and val:
            outputs[key] = f'https://{val}'
        else:
            outputs[key] = val
    except Exception:
        pass

json.dump(outputs, open('/tmp/outputs.json', 'w'))
print(f'Collected {len(outputs)} outputs')
print(json.dumps(outputs, indent=2))
" || { echo '{"deployment_id":"'${DEPLOYMENT_ID:-unknown}'","status":"success"}' > /tmp/outputs.json; }

echo "=== Deployment complete ==="
