"""
Documentation generator service for creating project documentation
"""

from pathlib import Path
from typing import Dict, Any
import logging
from datetime import datetime

from models.template import Template

logger = logging.getLogger(__name__)


class DocumentationGenerator:
    """Generates project documentation from templates"""

    def __init__(self):
        """Initialize documentation generator"""
        self.timestamp = datetime.now().isoformat()

    def generate_readme(
        self,
        template: Template,
        parameters: Dict[str, Any],
        framework_id: str = None,
        deployment_pattern_id: str = None
    ) -> str:
        """
        Generate README.md for bootstrapped project

        Args:
            template: Template metadata
            parameters: User-provided parameters
            framework_id: Selected framework
            deployment_pattern_id: Selected deployment pattern

        Returns:
            Generated README content
        """
        project_name = parameters.get("PROJECT_NAME", "my-project")

        # Get framework and pattern names
        framework_name = "Default"
        if framework_id:
            framework = template.get_framework(framework_id)
            framework_name = framework.name if framework else framework_id

        pattern_name = "Default"
        if deployment_pattern_id:
            pattern = template.get_deployment_pattern(deployment_pattern_id)
            pattern_name = pattern.name if pattern else deployment_pattern_id

        readme = f"""# {project_name}

Generated from template: **{template.metadata.name}** (v{template.metadata.version})

## Overview

{template.metadata.description}

**Pattern Type:** {template.metadata.pattern_type.value}
**Framework:** {framework_name}
**Deployment:** {pattern_name}
**Generated:** {self.timestamp}

## Quick Start

### Prerequisites

- Python 3.11+
- AWS CLI configured
- Terraform installed (if using Terraform)
- Docker (optional, for containerized deployment)

### Installation

1. Install dependencies:
   ```bash
   pip install -r requirements.txt
   ```

2. Configure environment:
   ```bash
   cp .env.example .env
   # Edit .env with your configuration
   ```

3. Run locally:
   ```bash
   python -m src.main
   ```

## Project Structure

```
{project_name}/
├── src/              # Application source code
├── iac/              # Infrastructure as Code
├── tests/            # Test files
├── requirements.txt  # Python dependencies
├── Dockerfile        # Container configuration
└── README.md        # This file
```

## Configuration

Environment variables:

```bash
PROJECT_NAME={project_name}
"""

        # Add parameter-specific configuration
        for param in template.metadata.parameters:
            if param.name in parameters:
                value = parameters[param.name]
                readme += f"{param.name.upper()}={value}\n"

        readme += """```

## Development

### Local Development

```bash
# Install dependencies
pip install -r requirements.txt

# Run tests
pytest tests/

# Run application
python -m src.main
```

### Deployment

"""

        if deployment_pattern_id == "terraform":
            readme += """
#### Deploy with Terraform

```bash
cd iac
terraform init
terraform plan
terraform apply
```
"""
        elif deployment_pattern_id == "cdk":
            readme += """
#### Deploy with AWS CDK

```bash
cd iac
npm install
cdk deploy
```
"""
        elif deployment_pattern_id == "cloudformation":
            readme += """
#### Deploy with CloudFormation

```bash
cd iac
aws cloudformation deploy --template-file template.yaml --stack-name {project_name}
```
"""

        readme += """
## Customization

This project was generated from a template. To customize:

1. **Implement Business Logic**: Add your specific logic in `src/`
2. **Configure Infrastructure**: Customize IaC in `iac/`
3. **Add Dependencies**: Update `requirements.txt` as needed
4. **Update Tests**: Add tests in `tests/`

## Example Use Cases

This template pattern is suitable for:

"""

        for use_case in template.metadata.example_use_cases:
            readme += f"- {use_case}\n"

        readme += f"""
## Architecture

See `ARCHITECTURE.md` for detailed architecture documentation.

## Documentation

- `README.md` - This file (getting started)
- `ARCHITECTURE.md` - System architecture
- `DEVELOPMENT.md` - Development guide

## Support

For issues and questions, see the AVA documentation.

## License

{template.metadata.license or 'Apache-2.0'}

---

Generated by AVA Control Plane
"""

        return readme

    def generate_architecture_doc(
        self,
        template: Template,
        framework_id: str = None,
        deployment_pattern_id: str = None
    ) -> str:
        """
        Generate ARCHITECTURE.md

        Args:
            template: Template metadata
            framework_id: Selected framework
            deployment_pattern_id: Selected deployment pattern

        Returns:
            Generated architecture documentation
        """
        framework_name = "Default"
        if framework_id:
            framework = template.get_framework(framework_id)
            framework_name = framework.name if framework else framework_id

        pattern_name = "Default"
        if deployment_pattern_id:
            pattern = template.get_deployment_pattern(deployment_pattern_id)
            pattern_name = pattern.name if pattern else deployment_pattern_id

        arch_doc = f"""# Architecture Documentation

## Overview

This document describes the architecture of your {template.metadata.pattern_type.value} application.

**Template:** {template.metadata.name}
**Version:** {template.metadata.version}
**Framework:** {framework_name}
**Deployment Pattern:** {pattern_name}

## Pattern Type: {template.metadata.pattern_type.value.replace('_', ' ').title()}

{template.metadata.description}

## Components

"""

        if template.metadata.pattern_type.value == "orchestration":
            arch_doc += """
### Orchestrator
- Coordinates multiple specialized agents
- Manages workflow and task routing
- Aggregates results from agents

### Agent A
- Specialized domain agent
- TODO: Define specific responsibilities

### Agent B
- Complementary domain agent
- TODO: Define specific responsibilities

### Communication
- Agents communicate through orchestrator
- Shared state management
- Result aggregation
"""
        elif template.metadata.pattern_type.value == "single_agent":
            arch_doc += """
### Main Agent
- Processes incoming requests
- Uses configured tools
- Returns structured responses

### Tools
- Domain-specific tools
- TODO: List your tools

### Handler
- Request routing
- Response formatting
"""

        arch_doc += f"""
## Technology Stack

### Framework
**{framework_name}**

"""

        if framework_id == "langraph":
            arch_doc += """
LangGraph provides:
- Stateful agent execution
- Graph-based workflows
- Tool integration
- Streaming support
"""
        elif framework_id == "strands":
            arch_doc += """
Strands SDK provides:
- Production-ready agent framework
- Built-in observability
- Tool management
- Error handling
"""

        arch_doc += f"""
### Infrastructure
**{pattern_name}**

"""

        if deployment_pattern_id == "terraform":
            arch_doc += """
Terraform manages:
- AWS resource provisioning
- Infrastructure as code
- State management
- Change planning
"""
        elif deployment_pattern_id == "cdk":
            arch_doc += """
AWS CDK manages:
- Cloud infrastructure with code
- TypeScript/Python definitions
- AWS service integration
- Stack deployment
"""

        arch_doc += """
## Data Flow

```
Request → Handler → Agent(s) → Tools → Processing → Response
```

TODO: Customize this data flow for your specific use case.

## Security Considerations

- Authentication: TODO: Configure authentication
- Authorization: TODO: Define access controls
- Data encryption: Use AWS KMS for sensitive data
- API keys: Store in AWS Secrets Manager
- Network security: Use VPC and security groups

## Scalability

- Horizontal scaling: Configure auto-scaling
- Vertical scaling: Adjust instance sizes
- Caching: Implement caching where appropriate
- Database: Use managed database services

## Monitoring

- Logs: CloudWatch Logs
- Metrics: CloudWatch Metrics
- Traces: Langfuse for LLM observability
- Alerts: Configure CloudWatch Alarms

## Deployment

See README.md for deployment instructions.

## Further Customization

To adapt this architecture for your use case:

1. Define specific agent responsibilities
2. Add domain-specific tools
3. Configure infrastructure for your scale
4. Implement business logic
5. Add monitoring and alerts

---

Template: {template.metadata.name} v{template.metadata.version}
Generated: {self.timestamp}
"""

        return arch_doc

    def generate_development_guide(
        self,
        template: Template,
        parameters: Dict[str, Any]
    ) -> str:
        """
        Generate DEVELOPMENT.md

        Args:
            template: Template metadata
            parameters: User-provided parameters

        Returns:
            Generated development guide
        """
        project_name = parameters.get("PROJECT_NAME", "my-project")

        dev_guide = f"""# Development Guide

## Getting Started

This guide helps you customize and extend your {template.metadata.pattern_type.value} application.

## Project Structure

```
{project_name}/
├── src/
│   ├── main.py          # Application entry point
│   ├── config.py        # Configuration management
│   └── ...              # Your application code
├── iac/
│   └── ...              # Infrastructure as Code
├── tests/
│   └── ...              # Test files
├── requirements.txt      # Python dependencies
└── Dockerfile           # Container configuration
```

## Development Workflow

### 1. Set Up Development Environment

```bash
# Create virtual environment
python -m venv venv
source venv/bin/activate  # On Windows: venv\\Scripts\\activate

# Install dependencies
pip install -r requirements.txt

# Install development dependencies
pip install pytest pytest-cov black flake8 mypy
```

### 2. Configure Environment

Create `.env` file:

```bash
# Copy example
cp .env.example .env

# Edit with your values
PROJECT_NAME={project_name}
AWS_REGION=us-east-1
# Add other configuration
```

### 3. Implement Business Logic

"""

        if template.metadata.pattern_type.value == "orchestration":
            dev_guide += """
#### Customize Orchestrator

Edit `src/orchestrator.py`:

```python
def orchestrate(self, task: Dict) -> Dict:
    # TODO: Implement your orchestration logic
    # - Sequential: Execute agents one by one
    # - Parallel: Execute agents concurrently
    # - Conditional: Route based on conditions
    pass
```

#### Implement Agent A

Edit `src/agents/agent_a.py`:

```python
def execute(self, task: Dict) -> Dict:
    # TODO: Implement Agent A logic
    # Define what this agent does
    pass
```

#### Implement Agent B

Edit `src/agents/agent_b.py`:

```python
def execute(self, task: Dict) -> Dict:
    # TODO: Implement Agent B logic
    # Define what this agent does
    pass
```
"""
        else:
            dev_guide += """
#### Implement Agent Logic

Edit your agent implementation:

```python
def execute(self, task: Dict) -> Dict:
    # TODO: Implement your agent logic
    pass
```
"""

        dev_guide += """
### 4. Add Tools

Create tools in `src/tools/`:

```python
from langchain.tools import Tool

def my_custom_tool(input: str) -> str:
    # TODO: Implement tool logic
    return result

tool = Tool(
    name="my_custom_tool",
    description="Description of what this tool does",
    func=my_custom_tool
)
```

### 5. Write Tests

Create tests in `tests/`:

```python
import pytest

def test_my_agent():
    # TODO: Test your agent
    assert True
```

Run tests:

```bash
pytest tests/ -v --cov=src
```

### 6. Code Quality

```bash
# Format code
black src/ tests/

# Lint code
flake8 src/ tests/

# Type check
mypy src/
```

## Configuration Parameters

"""

        for param in template.metadata.parameters:
            dev_guide += f"""
### {param.name}
- **Type:** {param.type}
- **Description:** {param.description}
- **Required:** {param.required}
"""
            if param.default:
                dev_guide += f"- **Default:** {param.default}\n"

        dev_guide += """
## Observability

### Langfuse Integration

Traces are automatically sent to Langfuse for observability.

View traces:
1. Navigate to your Langfuse dashboard
2. Select your project
3. View agent executions and performance

### Custom Instrumentation

Add custom traces:

```python
from langfuse import Langfuse

langfuse = Langfuse()

@langfuse.observe()
def my_function():
    # Your code here
    pass
```

## Deployment

### Local Testing

```bash
python -m src.main
```

### Deploy to AWS

```bash
cd iac
terraform init
terraform plan
terraform apply
```

## Troubleshooting

### Common Issues

1. **Import errors**: Ensure virtual environment is activated
2. **AWS credentials**: Configure AWS CLI with `aws configure`
3. **Dependency conflicts**: Update requirements.txt

### Debug Mode

Enable debug logging:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

## Best Practices

1. **Keep agents focused**: Each agent should have clear responsibilities
2. **Use type hints**: Add type annotations for clarity
3. **Write tests**: Test each component independently
4. **Document changes**: Update docs when changing architecture
5. **Use environment variables**: Never hardcode secrets

## Resources

- Template documentation: See README.md
- Architecture: See ARCHITECTURE.md
- AVA: Main project documentation

---

Template: {template.metadata.name} v{template.metadata.version}
Generated: {self.timestamp}
"""

        return dev_guide

    def generate_all_docs(
        self,
        template: Template,
        parameters: Dict[str, Any],
        framework_id: str = None,
        deployment_pattern_id: str = None
    ) -> Dict[str, str]:
        """
        Generate all documentation files

        Args:
            template: Template metadata
            parameters: User-provided parameters
            framework_id: Selected framework
            deployment_pattern_id: Selected deployment pattern

        Returns:
            Dictionary mapping filenames to content
        """
        docs = {
            "README.md": self.generate_readme(
                template, parameters, framework_id, deployment_pattern_id
            ),
            "ARCHITECTURE.md": self.generate_architecture_doc(
                template, framework_id, deployment_pattern_id
            ),
            "DEVELOPMENT.md": self.generate_development_guide(
                template, parameters
            )
        }

        logger.info(f"Generated {len(docs)} documentation files")
        return docs
